<a href="https://colab.research.google.com/github/Super-rookie-Py/PythonProgramming/blob/master/%EB%B0%95%EA%B1%B4%EC%9A%B0__02_%EB%B3%80%EC%88%98%2C_%EC%9E%90%EB%A3%8C%ED%98%95%2C_%EC%97%B0%EC%82%B0%EC%9E%90.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 변수, 자료형, 연산자
- keonwoo Park 2020/08/19






---




## 변수(Variables)

In [ ]:
name = "Keonwoo"
print(name)
num = 123
print(num)

Keonwoo
123


### 변수명 규칙


In [ ]:
abc = "abc"
abc_123 = 123
Abc_123 = 1234
print(abc)
print(abc_123)
print(Abc_123)

abc
123
1234




---



## 자료형(Data Types)



### 불리언형 자료형(Boolean Type)

* 불리언은 `True`와 `False` 값으로만 표현할 때 사용하는 자료형
* 예제 코드에서 변수 `b`에 `True` 값을 넣으면 불리언 자료형으로 결정
* 자료형을 반환하는 내장함수 `type()` 함수를 이용하여 자료형을 확인하면 `bool`로 반환된 결과를 볼 수 있음

In [ ]:
b = True
print(b)
print(type(b))

True
<class 'bool'>


### 정수형 자료형(Integer Type)

#### 10진수(Decimal) 

* 10진수는 일반적인 숫자 표현을 그대로 사용
* 변수 `i`에 10진수로 숫자 10을 값으로 넣고, `type()` 함수를 통해 자료형을 확인하기


In [ ]:
i = 10
print(i)
print(type(i))

10
<class 'int'>


#### 2진수(Binary)

* 2진수는 앞에 `0b`를 붙여서 표현
* 변수 `b`에 2진수 표현으로 `0b010`을 넣고, `type()` 함수를 통해 자료형을 확인하기

In [ ]:
b = 0b010
print(b)
print(type(b))

2
<class 'int'>


#### 8진수(Octal)

* 8진수는 앞에 `0o`를 붙여서 표현
* 변수 `o`에 8진수 표현으로 `0o130`을 넣고 확인하기

In [ ]:
o = 0o130
print(o)
print(type(o))

88
<class 'int'>


#### 16진수(Hexadecimal)

* 16진수은 앞에 `0x`를 붙여서 표현
* 변수 `h`에 16진수 표현으로 `0xABC`를 넣고 확인하기
* 16진수는 10진수와 달리 10부터 A에서 F까지 알파벳을 사용하여 표현

In [ ]:
h = 0xABC
print(h)
print(type(h))

2748
<class 'int'>


### 실수형 자료형(Floating-Point Type)

* 실수형 자료형 표현은 고정소수점과 부동소수점으로 구분

#### 고정소수점(Fixed-Point)

* 기본적으로 고정된 자리수의 소수를 사용하는 고정소수점 방식
* 실수형 변수 `f`에 소수점이 포함된 `12.34` 값을 넣고 확인하기
* `type(f)`를 통해서 결과를 확인해보면 실수형(float) 자료형으로 출력
* 파이썬에서는 소수에서 정수부가 0인 경우에는 제외해서 표현 가능
* 코드에서 값 `.123`은 `0.123`을 의미

In [ ]:
f = 12.34
print(f)
print(type(f))

12.34
<class 'float'>


In [ ]:
f = .123
print(f)

0.123


#### 부동소수점(Floating-Point)

* 컴퓨터에서 소수점의 위치가 고정되지 않고 넓은 범위의 값을 근사하여 표현하는 부동소수점 방식이 있음
* 부동소수점에 대한 개념을 모르는 경우에는 [링크](https://ko.wikipedia.org/wiki/%EB%B6%80%EB%8F%99%EC%86%8C%EC%88%98%EC%A0%90)를 참고
* 파이썬에서는 e 기호를 이용하여 지수에 대한 표현을 사용
* `e` 변수에 할당한 `1234e-2` 라는 표현은 $1234 \times 10^{-2}$를 의미하고 실제 결과 값은 12.34
* `type(e)` 함수를 통해 타입을 확인해보면 실수형
* 마찬가지로 `123e-3`은 $123 \times 10^{-3}$를 의미하며 결과는 0.123

In [ ]:
e = 1234e-2
print(e)
print(type(e))

12.34
<class 'float'>


In [ ]:
e = 123e-3
print(e)

0.123


###복소수형 자료형(Complex Type)

* 복소수(complex number)는 임의의 실수 $a$, $b$에 대해 $a + bi$의 꼴로 나타내는 수를 의미
* 여기서 $a$는 실수, $b$는 허수 부분
* i는 제곱하여 -1이 되는 수로 허수(imaginary number) 단위라고 함
* 복소수에 대한 개념을 모르는 경우에는 [링크](https://ko.wikipedia.org/wiki/%EB%B3%B5%EC%86%8C%EC%88%98) 참고
* 파이썬에서는 i 대신에 j 또는 J로 표현
* $1 + 23j$와 같이 복소수로 표현하기
* `print()` 함수를 이용해 출력한 결과 `(1+23j)`
* 실수부는 `c.real`로 허수부는 `c.imag`로 출력
* 복소수의 경우에는 `type()` 함수로 타입을 살펴보면 결과는 'complex'

In [ ]:
c = 1 + 23j
print(c)
print(c.real)
print(c.imag)
print(type(c))

(1+23j)
1.0
23.0
<class 'complex'>


### 문자열 자료형(String Type)

* 문자열(string)은 문자들의 집합을 의미
* 문자열을 저장하는 변수를 문자열 변수라고 함

In [ ]:
string = "Keonwoo"
print(string)
print(type(string))

Keonwoo
<class 'str'>


### 리스트 자료형(List Type)

* 리스트(list)는 여러 값을 하나의 변수에 담을 수 있는 자료형
* 대괄호 안에 여러 값을 쉽표를 구분자로 표현하여 리스트 변수 생성
* 간단하게 리스트 생성과 출력을 위해 변수 `l` 안에 값 1, 2, 3을 넣어보자
* 자료형을 출력해보면 'list'라는 결과 값을 가지는 것을 알 수 있음

In [ ]:
l = [i for i in range(1,4)]
print(l)
print(type(l))

[1, 2, 3]
<class 'list'>


* 리스트 자료형은 같은 자료형이 아니라 다른 자료형을 가지는 값들도 포함하여 구성 가능
* 숫자와 문자열이 포함된 리스트 변수 사용하기

In [ ]:
l = [1,'One',2,'Two']
print(l)
print(type(l))

[1, 'One', 2, 'Two']
<class 'list'>


### 튜플 자료형(Tuple Type)

* 튜플 자료형은 리스트 자료형과 유사하지만 생성, 삭제, 수정이 불가
* 튜플은 괄호 안에 여러 값을 쉼표로 구분하여 사용
* 변수 `t` 안에 값 1, 2, 3을 저장하고, 변수와 변수의 타입을 출력하기

In [ ]:
t = (1, 2, 3)
print(t)
print(type(t))

(1, 2, 3)
<class 'tuple'>


### 범위 자료형(Range Type)

* 불변한 숫자 시퀀스 자료형

In [ ]:
r = range(10)
print(r)
print(type(r))

range(0, 10)
<class 'range'>


### 집합 자료형(Set Type)

* 집합 자료형은 중복과 순서가 없다는 특징을 가지며 집합 처리를 쉽게할 수 있음
* 집합은 중괄호를 이용해서 값을 쉼표로 구분하여 넣음
* 변수 `s` 안에 값 2, 3, 1을 넣고 변수 `s`의 값과 타입을 출력한 예제
* 변경 불가능한 집합 자료형으로 fronzenset이 있음

In [ ]:
s = {2, 3, 1}
print(s)
print(type(s))

fs = frozenset(s)
print(fs)
print(type(fs))

{1, 2, 3}
<class 'set'>
frozenset({1, 2, 3})
<class 'frozenset'>


### 딕셔너리 자료형(Dictionary Type)

* 딕셔너리 자료형은 다른 자료형과 달리 키(key)와 값(value)를 한 쌍으로 갖는 자료형
* 변수 `d`에 키와 값을 구분자 `:`를 이용해서 쌍으로 묶어서 `1: 'One', 2: 'Two'` 형태로 넣을 수 있음

In [ ]:
dic = {1: "One", 2: "Two", 3:"Three"}
print(dic)
print(type(dic))

{1: 'One', 2: 'Two', 3: 'Three'}
<class 'dict'>


### 바이트 시퀀스형(Byte Sequence Type)

* 바이트 자료형은 1바이트 단위의 값을 연속적으로 저장하는 시퀀스 자료형
* 1바이트는 8비트에 해당하며, 정수값 0 ~ 255(0x00~0xFF) 사용
* 이진 데이터로 사용되어지거나 1바이트 문자로 고정을 위해 사용
* 유니코드가 아닌 문자열을 사용하는 것과 유사
* 바이트 자료형의 시퀀스 형태로 `bytearray` 자료형 사용
* 바이트 자료형의 메모리 값의 표현으로 `memoryview` 자료형 사용


In [ ]:
byte = b'\x00'
print(byte)
print(type(byte))

byte = b"Hello"
print(byte)
print(type(byte))

ba = bytearray(byte)
print(ba)
print(type(ba))

mv = memoryview(ba)
print(mv)
print(type(mv))

b'\x00'
<class 'bytes'>
b'Hello'
<class 'bytes'>
bytearray(b'Hello')
<class 'bytearray'>
<class 'memoryview'>




---



## 자료형 변환

#### bool()

* `bool()` 함수는 다양한 자료형을 불리언형으로 변환
* `0`이나 `False` 값이 아닌 경우는 모두 True로 변환

In [ ]:
print(bool(True))
print(bool(False))
print(bool(10))
print(bool(0b010))
print(bool(0o130))
print(bool(0xABC))
print(bool(12.34))
print(bool(1234e-2))
print(bool('10'))
print(bool(0))

True
False
True
True
True
True
True
True
True
False


### int()

* `int()` 함수는 다양한 자료형을 정수형으로 변환
* 복소수형은 정수로 `int()` 함수를 통해 변환이 되지 않음
* 불리언 형은 값으로 `True`와 `False`만 가지고 `int()` 함수를 통해 정수로 변환되면 `True`는 1로 `False`는 0으로 변환
* 정수값 10과 2진수 `0b010`, 8진수 `0o130`, 16진수 `0xABC`는 모두 같은 정수형이라서 그대로 값을 유지하고, 10진수 형태로 변환되어 출력
* 실수형을 정수형으로 변환하는 경우에는 고정소수점이든 부동소수점이든지 소수점 이하를 제외하고 변환, 예를 들어, 12.34는 12로 소수점을 제외하고 변환
* 문자형은 기본적으로는 문자열을 10진수 변환, 예를 들어, `int('10')`은 기본 10진수로 문자열 '10'을 정수형 10으로 변환
* 2진수, 8진수, 16진수 등의 다른 진수로 된 문자열일 경우에는 몇 진수에 해당되는지를 입력해주면 그에 맞추어 변환
* `int('010', 2)`와 같이 문자열 '010'을 2진수라고 알려주고 변환하기 위해서 2라고 입력하고, 8진수과 16진수도 마찬가지

In [ ]:
print(int(True))
print(int(False))
print(int(10))
print(int(0b010))
print(int(0o130))
print(int(0xABC))
print(int(12.34))
print(int(1234e-2))
print(int('10'))
print(int(0))
print(int('010',2))
print(int('130',8))
print(int('ABC',16))

1
0
10
2
88
2748
12
12
10
0
2
88
2748


### float()

* `float()` 함수는 자료형을 실수형으로 변환
* 복소수형은 변환이 되지 않고, 문자열 형태의 2진수, 8진수, 16진수도 변환이 되지 않음
* `int()` 함수를 사용한 결과와 유사하지만, 소수점 이하 값이 포함
* 만약 소수점 이하 값이 없다면 .0으로 변환되고, 소수점 이하 값이 있는 실수형은 동일한 값으로 변환

In [ ]:
print(float(True))
print(float(False))
print(float(10))
print(float(0b010))
print(float(0o130))
print(float(0xABC))
print(float(12.34))
print(float(1234e-2))
print(float('10'))
print(float(0))

1.0
0.0
10.0
2.0
88.0
2748.0
12.34
12.34
10.0
0.0


### complex()

* `complex()` 함수는 자료형을 복소수형으로 변환
* 불리언형, 정수형, 실수형, 복소수형, 문자형 모두 복소수형으로 변환 가능
* 허수가 있는 복소수형을 제외하고 다른 자료형은 허수 부분이 없어서 `OJ`로 변환

In [ ]:
print(complex(True))
print(complex(False))
print(complex(10))
print(complex(0b010))
print(complex(0o130))
print(complex(0xABC))
print(complex(12.34))
print(complex(1234e-2))
print(complex('10'))
print(complex(0))
print(complex(1 + 23j))

(1+0j)
0j
(10+0j)
(2+0j)
(88+0j)
(2748+0j)
(12.34+0j)
(12.34+0j)
(10+0j)
0j
(1+23j)


### str()

* `str()` 함수는 파이썬의 모든 자료형을 문자열로 변환
* 자료형의 값을 그대로 문자열 형태로 변환


In [ ]:
print(str(True))
print(str(False))
print(str(10))
print(str(0b010))
print(str(0o130))
print(str(0xABC))
print(str(12.34))
print(str(1234e-2))
print(str('10'))
print(str(0))
print(str(1 + 23j))
print(str([1, 2, 3]))
print(str((1, 2, 3)))
print(str({2, 3, 1}))
print(str({1: 'one', 2:' two'}))

True
False
10
2
88
2748
12.34
12.34
10
0
(1+23j)
[1, 2, 3]
(1, 2, 3)
{1, 2, 3}
{1: 'one', 2: ' two'}


### eval()

* `eval()` 함수는 문자열에 포함된 수식을 계산하여 나온 결과를 반환
* '1 + 2'라는 문자열에 대해서 그대로 출력하는 것과 달리 계산된 결과 값은 3을 출력
* 그 밖에도 -, *, /와 같은 여러 수식들에 대해서도 계산 가능

In [ ]:
print("1+2")
print(eval("1+2"))
print(eval("10+ 20 - 39"))
print(eval("10 *10"))
print(eval("100/ 10"))

1+2
3
-9
100
10.0


### tuple()

* `tuple()` 함수는 문자열, 리스트, 튜플 등의 자료형을 튜플 자료형으로 변환
* 문자열 `'Suan'`을 문자 단위로 구분하여 튜플 자료형으로 변환
* 리스트 자료형 `[1, 2, 3]`이나 튜플 자료형 `(1, 2, 3)`도 튜플 자료형으로 `(1, 2, 3)`으로 변환

In [ ]:
print(tuple('keonwoo'))
print(tuple([1,2,3]))
print(tuple((1,2,3)))

('k', 'e', 'o', 'n', 'w', 'o', 'o')
(1, 2, 3)
(1, 2, 3)


### list()

* `list()` 함수는 문자열, 리스트, 튜플 등의 자료형을 리스트 자료형으로 변환
* 문자열 `'Suan'`, 리스트 `[1, 2, 3]`, 튜플 `(1, 2, 3)`에 대해서 리스트 자료형으로 변환

In [ ]:
print(list('keonwoo'))
print(list([1,2,3]))
print(list((1,2,3)))

['k', 'e', 'o', 'n', 'w', 'o', 'o']
[1, 2, 3]
[1, 2, 3]


### set()

* `set()` 함수는 문자열, 리스트, 튜플, 집합, 딕셔너리 자료형을 집합 자료형으로 변환
* 집합의 특성답게 요소에 대해서 순서를 고려하지 않고 변환
* 리스트, 튜플, 집합 자료형도 집합 형태로 변환이 되며, 딕셔너리 자료형도 집합으로 변환
* 딕셔너리 자료형은 키와 값으로 구성된 구조에서 키 값에 해당하는 것만 집합으로 변환


In [ ]:
print(set('keonwoo'))
print(set([1,2,3]))
print(set((1,2,3)))
print(set({1,2,3}))
print(set({1:'One', 2:'Two'}))

{'o', 'k', 'n', 'w', 'e'}
{1, 2, 3}
{1, 2, 3}
{1, 2, 3}
{1, 2}


### frozenset()

* `frozenset()` 함수는 문자열을 고정 집합 형태로 변환
* `set()` 함수는 집합의 값을 추가 및 제거 등이 가능
* `frozenset()` 함수는 수정 불가능한 집합 자료형

In [ ]:
print(frozenset('Keonwoo'))
print(frozenset([1, 2, 3]))

frozenset({'o', 'n', 'K', 'w', 'e'})
frozenset({1, 2, 3})


### dict()

* `dict()` 함수는 딕셔너리 자료형으로 변환하는 역할
* (키: 값)으로 구성된 튜플의 시퀀스 형태로 값을 가짐


In [ ]:
print(dict({1:'One', 2: 'Two'}))
print(dict({"One":1 , "Two": 2}))

{1: 'One', 2: 'Two'}
{'One': 1, 'Two': 2}


### chr()

* `chr()` 함수는 정수를 문자로 변환
* 컴퓨터에서는 문자를 처리하기 위해 각 문자마다 특정 정수값으로 매핑: ASCII(American Standard Code for Information Interchange)

* `chr()` 함수는 ASCII 기준에 따라서 정수값에 해당하는 문자를 나타냄
* 예를 들어, ASCII에서 정수 값 97은 문자 a에 매핑되어 `chr(97)`의 결과 값은 문자 a

In [ ]:
print(chr(97))
print(chr(65))
print(chr(122))
print(chr(90))

a
A
z
Z


### ord()

* `ord()` 함수는 `chr()` 함수와 반대로 문자를 정수 값으로 변환
* ASCII에 맞춰서 문자 'a'에 해당하는 정수 값인 97을 출력하기

In [ ]:
print(ord('A'))
print(ord('a'))
print(ord('z'))
print(ord('Z'))

65
97
122
90


### bin()

* `bin()` 함수는 정수를 2진수 문자열로 변환
* 자료형을 2진수 표기인 '0b'가 붙은 형태의 문자열로 변환
* `bin()` 함수로 `True`는 `0b1`로 출력하고, `False`는 `0b0`으로 출력하기
* 10진수, 2진수, 8진수, 16진수 정수형도 2진수로 변환되어 출력

In [ ]:
print(bin(True))
print(bin(False))
print(bin(10))
print(bin(0b010))
print(bin(0o130))
print(bin(0xABC))

0b1
0b0
0b1010
0b10
0b1011000
0b101010111100


### oct()

* `oct()` 함수는 정수를 8진수 문자열로 변환
* 불리언형, 정수형 등의 자료형을 8진수 표기인 '0o'가 붙은 형태의 문자열로 변환
* `oct()` 함수를 이용해 `True`는 `0o1`로 출력되고, `False`는 `0o0`으로 출력하기
* 10진수, 2진수, 8진수, 16진수 정수형도 8진수로 변환되어 출력

In [ ]:
print(oct(True))
print(oct(False))
print(oct(10))
print(oct(0b010))
print(oct(0o130))
print(oct(0xABC))

0o1
0o0
0o12
0o2
0o130
0o5274


### hex()

* `hex()` 함수는 정수를 16진수 문자열로 변환
* 주어진 자료형을 16진수 표기인 '0x'가 붙은 16진수 형태의 문자열로 변환
* 불리언형과 정수형 모두 16진수 표기의 문자열로 변환하기


In [ ]:
print(hex(True))
print(hex(False))
print(hex(10))
print(hex(0b010))
print(hex(0o130))
print(hex(0xABC))

0x1
0x0
0xa
0x2
0x58
0xabc


### bytes()

* `bytes()` 함수는 자료형을 바이트형으로 변환
* 객체를 바이트 객체로 변환

In [ ]:
print(bytes(True))
print(bytes(False))
print(bytes(10))
print(bytes(b'Hello'))
print(bytes([1, 2, 3]))

b'\x00'
b''
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'Hello'
b'\x01\x02\x03'


### bytearray()

* `bytearray()` 함수는 자료형을 변경가능한 바이트형으로 변환

In [ ]:
ba = bytearray(b'hello')
print(ba)
ba[0] = ord('H')
print(ba)
ba[0]= 65
print(ba)
print(type(ba))

ba = bytearray([1, 2, 3])
print(ba)
ba[0] = 4
print(ba)
print(type(ba))

bytearray(b'hello')
bytearray(b'Hello')
bytearray(b'Aello')
<class 'bytearray'>
bytearray(b'\x01\x02\x03')
bytearray(b'\x04\x02\x03')
<class 'bytearray'>


### memoryview()

* 바이트 자료형을 메모리의 이진 데이터로 변환한 자료형

In [ ]:
ba = bytearray(b'hello')
mv = memoryview(ba)
ba[0] = 72
print(ba)
print(mv)
print(type(mv))

bytearray(b'Hello')
<class 'memoryview'>


## 자료형 계산

### min()

* 입력된 값들 중에서 가장 작은 값을 반환하는 함수

In [ ]:
li = [1,2,3]
i = 10
min(li[0],i)
print(min(1, 2, 3))

1


### max()

* 입력된 값들 중에서 가장 큰 값을 반환하는 함수

In [ ]:
print(max(1,2, 3))
print(max([3, 4, 5]))

3
5


### sum()

* 입력된 값들의 전체 합을 반환

In [ ]:
print(sum((1, 2, 3)))
print(sum([3, 4, 5]))

6
12


### divmod()

* 나눈 값과 나머지 값을 쌍으로 반환
* `(a // b, a % b)`와 동일한 값

In [ ]:
print(divmod(3, 5))
print(divmod(10, 5))
print((10 // 5, 10 %5))

(0, 3)
(2, 0)
(2, 0)


### abs()

* 절대값 $|x|$으로 반환 

In [ ]:
print(abs(-4))
print(abs(5))
print(abs(-10))

4
5
10


### pow()

* 지수승의 값 $a^b$으로 반환

In [ ]:
print(pow(2, 3))
print(pow(10,4))

8
10000


### len(s)

* 다양한 시퀀스의 갯수를 반환

In [ ]:
print(len("String"))
print(len((1, 2, 3)))
print(len([4, 5, 6]))

6
3
3


### round()

* 소수점 뒤를 반올림한 값을 반환

In [ ]:
print(round(3.14))
print(round(3.141592,2))
print(round(0.6))
print(round(0.4))

3
3.14
1
0


### all()

* 모든 값이 `True` 이거나 비어있을 때 `True` 반환

In [ ]:
a = [True]*10
print(a)
b = []
print(all(a))
print(all(b))
print(all((1, 2, 3)))
print(all((False,True)))
print(all((False, False, False)))

[True, True, True, True, True, True, True, True, True, True]
True
True
True
False
False


### any()

* 어떤 값이 `True` 이면 `True` 반환
* 값이 비어있으면 `False` 반환

In [ ]:
print(any((1, 2, 3)))
print(any((False,True)))
print(any((False, False, False)))
print(any([]))

True
True
False
False




---



# 연산자(Operators)



## 산술 연산자(Arithmetic Operators)



In [ ]:
a = 6
b = 4
print(a+b)
print(a-b)
print(a* b)
print(a/b)
print(a%b)
print(a **b)
print(a//b)

10
2
24
1.5
2
1296
1


## 비교 연산자(Comparison Operators)



# 새 섹션

In [ ]:
a , b = 6, 4
print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >=b)
print(a <=b)

False
True
True
False
True
False


## 할당 연산자(Assignment Operators)



In [ ]:
a , b = 6, 4
print(a, b)
a +=b
print(a)
a -=b
print(a)
a *= b
print(a)
a /= b
print(a)
a %= b
print(a)
a **=b 
print(a)
a //=b
print(a)

6 4
10
6
24
6.0
2.0
16.0
4.0


## 비트 연산자(Bitwise Operators)


In [ ]:
a, b = 6,4
print(bin(a))
print(bin(b))
print(a & b, bin(a & b))
print(a | b, bin(a | b))
print(a ^ b, bin(a ^ b))
print(~a, bin(~a))
print(a << b, bin(a << b))
print(a >> b, bin(a >> b))

0b110
0b100
4 0b100
6 0b110
2 0b10
-7 -0b111
96 0b1100000
0 0b0


## 논리 연산자(Logical Operators)


In [ ]:
print(True and True)
print(True and False)
print(True or False)
print(not True)
print(not False)
print(not (True and False))

True
False
True
False
True
True


## 멤버 연산자(Membership Operators)


In [ ]:
a, b = 6, 4
l = [2, 4 ,8]
print(a in l)
print(b in l)
print(a not in l)
print(b not in l)

False
True
True
False


## 식별 연산자(Identity Operators)


In [ ]:
a, b = 6, 4
print(a is b)
print(a is not b)
a, b = 5, 5
print(a is b)
print(a is not b)

False
True
True
False
